<template>
  <div class="run-selection-inspector">
    <InspectorSection :title="sectionTitle" :badge="statusLabel">
      <div class="selection-status">
        <span class="selection-status__mark" :class="`is-${statusValue}`" aria-hidden="true">{{ statusMark }}</span>
        <strong>{{ statusLabel }}</strong>
      </div>
      <InspectorPropertyList :rows="rows" />
      <button v-if="selectedSymbol?.type === 'acg'" type="button" class="inspector-link" @click="emit('locateGraph')">打开 graph.acg</button>
    </InspectorSection>

    <InspectorSection v-if="selectedSymbol?.type === 'model' && selectedSymbol.children.length" title="Output" badge="collapsed by default">
      <span class="inspector-hint">Structured Output 已保留在 Run Document 中，展开对应 Symbol 查看。</span>
    </InspectorSection>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { WorkspaceEntry, WorkspaceGraphNode } from '@/services/api/agentos'
import InspectorPropertyList, { type InspectorProperty } from '@/components/workbench/InspectorPropertyList.vue'
import InspectorSection from '@/components/workbench/InspectorSection.vue'
import type { RuntimeObservation } from '@/workbench/runtime/observation'
import type { RuntimeEventStore } from '@/workbench/runtime/runtimeEvents'
import type { RunDocumentSymbol } from '@/workbench/runtime/runDocument'

const props = defineProps<{
  entry: WorkspaceEntry | null
  selectedSymbol: RunDocumentSymbol | null
  graphNode: WorkspaceGraphNode | null
  graphNodes: WorkspaceGraphNode[]
  runId: string | null
  runStatus: string | null
  historical: boolean
  runtimeObservation?: RuntimeObservation | null
  runtimeStore?: RuntimeEventStore | null
}>()

const emit = defineEmits<{ locateGraph: [] }>()

const statusValue = computed(() => props.selectedSymbol?.status || props.graphNode?.status || props.entry?.status || props.runStatus || 'pending')
const statusLabel = computed(() => props.selectedSymbol?.status || props.graphNode?.status || props.entry?.status || props.runStatus || '未观测')
const statusMark = computed(() => ({ running: '●', completed: '✓', warning: '!', failed: '×', pending: '○' }[statusValue.value] || '○'))
const sectionTitle = computed(() => {
  if (props.selectedSymbol) {
    if (props.selectedSymbol.type === 'runtime') return 'STRUCTURED OUTPUT'
    if (props.selectedSymbol.type === 'planner') return 'PLANNING'
    return props.selectedSymbol.type.toUpperCase()
  }
  return 'RUN'
})

const symbolMetric = (key: string) => props.selectedSymbol?.metrics?.[key]
const childMetric = (title: string, key: string) => props.selectedSymbol?.children.find(item => item.title === title)?.metrics?.[key]
const agentName = computed(() => props.selectedSymbol?.children.find(item => item.type === 'agent')?.subtitle || null)
const rows = computed<InspectorProperty[]>(() => {
  const symbol = props.selectedSymbol
  if (!symbol) return [
    { label: 'Run ID', value: props.runId, code: true },
    { label: 'Status', value: props.runStatus || '未观测' },
    { label: 'Mode', value: props.historical ? 'Historical / Read-only' : 'Read-only' }
  ]
  if (symbol.type === 'planner') return [
    { label: 'Stage', value: symbol.children.find(item => item.status === 'running')?.title || 'Planning' },
    { label: 'Task Count', value: symbolMetric('Task Count') ?? symbolMetric('taskCount') ?? childMetric('Task Plan', 'taskCount') ?? '未观测' },
    { label: 'Dependency Count', value: symbolMetric('Dependency Count') ?? symbolMetric('dependencyCount') ?? childMetric('Task Plan', 'dependencyCount') ?? '未观测' },
    { label: 'Run ID', value: symbol.runId, code: true }
  ]
  if (symbol.type === 'execution') return [
    { label: 'Task Count', value: symbol.children.length },
    { label: 'Status', value: statusLabel.value },
    { label: 'Run ID', value: symbol.runId, code: true }
  ]
  if (symbol.type === 'task' || symbol.type === 'acg-node') return [
    { label: 'Name', value: symbol.title },
    { label: 'Status', value: statusLabel.value },
    { label: 'Agent', value: agentName.value || '未观测' },
    { label: 'semanticTaskKey', value: symbol.semanticTaskKey, code: true },
    { label: 'ACG Node', value: symbol.graphNodeId, code: true }
  ]
  if (symbol.type === 'tool') return [
    { label: 'Name', value: symbol.title },
    { label: 'Status', value: statusLabel.value },
    { label: 'Duration', value: symbolMetric('Duration') != null ? `${symbolMetric('Duration')} ms` : '未观测' },
    { label: 'Task', value: symbolMetric('Task') },
    { label: 'Run ID', value: symbol.runId, code: true }
  ]
  if (symbol.type === 'artifact') return [
    { label: 'Name', value: symbol.title },
    { label: 'Type', value: symbol.subtitle },
    { label: 'Generated By', value: symbolMetric('Task') },
    { label: 'artifactKey', value: symbol.artifactKey, code: true },
    { label: 'artifactId', value: symbol.artifactId, code: true }
  ]
  if (symbol.type === 'model') return [
    { label: 'Model', value: symbol.title },
    { label: 'Attempt', value: symbolMetric('Attempt') },
    { label: 'TTFT', value: symbolMetric('TTFT') != null ? `${symbolMetric('TTFT')} ms` : '未观测' },
    { label: 'Idle', value: symbolMetric('Idle') != null ? `${symbolMetric('Idle')} ms` : '未观测' },
    { label: 'Chunks', value: symbolMetric('Chunks') }
  ]
  if (symbol.type === 'acg') return [
    { label: 'Nodes', value: symbolMetric('Nodes') },
    { label: 'Edges', value: symbolMetric('Edges') },
    { label: 'Graph ID', value: props.entry?.graphId, code: true },
    { label: 'Run ID', value: symbol.runId, code: true }
  ]
  if (symbol.type === 'result') return [
    { label: 'Result', value: symbol.title },
    { label: 'Status', value: statusLabel.value },
    { label: 'Summary', value: symbol.subtitle },
    { label: 'Run ID', value: symbol.runId, code: true }
  ]
  if (symbol.type === 'runtime') return [
    { label: 'Output', value: symbol.title },
    { label: 'Format', value: symbol.subtitle || 'structured' },
    { label: 'Run ID', value: symbol.runId, code: true }
  ]
  return [
    { label: 'Title', value: symbol.title },
    { label: 'Status', value: statusLabel.value },
    { label: 'Run ID', value: symbol.runId, code: true }
  ]
})
</script>

<style scoped>
.run-selection-inspector { display: contents; }
.selection-status { display: flex; align-items: center; gap: 8px; min-height: 30px; margin-bottom: 4px; color: var(--wb-text); }
.selection-status strong { font-size: 13px; font-weight: 650; }
.selection-status__mark { width: 15px; color: var(--wb-text-muted); font: 12px var(--font-mono, monospace); text-align: center; }
.selection-status__mark.is-running { color: var(--wb-accent); }
.selection-status__mark.is-completed { color: var(--wb-success); }
.selection-status__mark.is-warning { color: var(--wb-warning); }
.selection-status__mark.is-failed { color: var(--wb-danger); }
.inspector-link { margin-top: 11px; padding: 0; border: 0; color: var(--wb-accent); background: transparent; cursor: pointer; font-size: 11px; }
.inspector-link:hover { text-decoration: underline; }
.inspector-hint { color: var(--wb-text-muted); font-size: 11px; line-height: 1.55; }
</style>
