import asyncio
import importlib
from typing import Any, Dict, List
from unittest.mock import patch

from agentos.core.models.types import SkillRequest
from agent.packs.writer.skills import (
    CharacterRelationSkill,
    ContentWriteSkill,
    InspirationExpandSkill,
    OutlineGenerateSkill,
)


class FakeAIService:
    async def generate_text(self, text: str, role_id: str = None, context: List[Dict[str, str]] = None, **kwargs) -> Dict[str, Any]:
        prompt = text or ""
        lowered = prompt.lower()

        if "creative_tree" in lowered or "inspiration" in lowered:
            return {
                "text": (
                    '{"creative_tree":{"id":"root","label":"Time Traveler Story","description":"core premise",'
                    '"children":[{"id":"root.world","label":"World","description":"future dystopia","children":[]},'
                    '{"id":"root.hero","label":"Hero","description":"engineer protagonist","children":[]}]}}'
                )
            }
        if "outline" in lowered and "chapter" in lowered:
            return {
                "text": (
                    "# Story Outline\n\n## Core Idea\nTime traveler prevents collapse.\n\n"
                    "## Chapter 1\n- Goal: Introduce conflict\n- Key event: Failed rescue\n- Emotional beat: Fear\n\n"
                    "## Chapter 2\n- Goal: Build alliance\n- Key event: Mentor appears\n- Emotional beat: Hope\n"
                )
            }
        if "relation_graph" in lowered or "relationship graph" in lowered:
            return {
                "text": (
                    '{"relation_graph":{"nodes":[{"id":"A","label":"A","group":"protagonist"},'
                    '{"id":"B","label":"B","group":"antagonist"}],'
                    '"edges":[{"from":"A","to":"B","label":"conflict"}]}}'
                )
            }
        if "fiction writer" in lowered or "chapter" in lowered:
            return {"text": "Chapter text generated by fake model."}

        return {"text": "{}"}


def _build_request(text: str, action_input: Dict[str, Any]) -> SkillRequest:
    return SkillRequest(
        sessionId="writer-test-session",
        text=text,
        actionInput=action_input,
        memory={"history": [{"role": "user", "content": text}]},
    )


async def _assert_timeout_fallback(skill, request: SkillRequest) -> None:
    module = importlib.import_module(skill.__class__.__module__)

    async def _timeout_wait_for(coro, timeout):
        try:
            coro.close()
        except Exception:
            pass
        raise asyncio.TimeoutError

    with patch.object(module.asyncio, "wait_for", new=_timeout_wait_for):
        result = await skill.run(request)
    assert result.success is True
    assert (
        "timeout" in result.message.lower()
        or "超时" in result.message
        or result.output.get("fallback_reason") == "timeout"
    )


async def test_inspiration_expand_skill():
    skill = InspirationExpandSkill(ai_service=FakeAIService())
    request = _build_request("time traveler saves world", {"premise": "time traveler saves world"})
    result = await skill.run(request)
    assert result.success is True
    assert "creative_tree" in result.output
    await _assert_timeout_fallback(skill, request)


async def test_outline_generate_skill():
    skill = OutlineGenerateSkill(ai_service=FakeAIService())
    request = _build_request(
        "generate outline",
        {"creative_selection": "time traveler saves world", "chapters_count": 6},
    )
    result = await skill.run(request)
    assert result.success is True
    assert "outline_markdown" in result.output
    await _assert_timeout_fallback(skill, request)


async def test_content_write_skill():
    skill = ContentWriteSkill(ai_service=FakeAIService())
    request = _build_request(
        "write chapter",
        {
            "outline_context": "Chapter 1 introduces conflict",
            "chapter_index": 1,
            "style": "Lu Xun style",
        },
    )
    result = await skill.run(request)
    assert result.success is True
    assert "content" in result.output
    await _assert_timeout_fallback(skill, request)


async def test_character_relation_skill():
    skill = CharacterRelationSkill(ai_service=FakeAIService())
    request = _build_request(
        "build relation graph",
        {
            "story_description": "A confronts B in a dystopian city",
            "character_list": ["A", "B"],
        },
    )
    result = await skill.run(request)
    assert result.success is True
    graph = result.output.get("relation_graph", {})
    assert isinstance(graph.get("nodes", []), list)
    assert isinstance(graph.get("edges", []), list)
    await _assert_timeout_fallback(skill, request)


async def _main():
    await test_inspiration_expand_skill()
    print("[PASS] inspiration_expand")
    await test_outline_generate_skill()
    print("[PASS] outline_generate")
    await test_content_write_skill()
    print("[PASS] content_write")
    await test_character_relation_skill()
    print("[PASS] character_relation_map")


if __name__ == "__main__":
    asyncio.run(_main())
